### ISSUE TITLE
React.memo 사용 시 eslint 에러!! (Component-definition-is-missing-display-name)

### ISSUE THREAD

**Issue by jsc7727** [upether/upeth-client#18]
# [eslint 에러!! Component-definition-is-missing-display-name-에러](https://velog.io/@yiseul/Component-definition-is-missing-display-name-%EC%97%90%EB%9F%AC)

React.memo 사용 시 display-name을 선언해줘야 합니다.

- tip
useMemo와 React.memo 차이점 
React.memo는 불필요한 컴포넌트 렌더링을 방지할 때 사용.
useMemo는 메모가 된 값을 return하는 hook이다.

**Comment by taekyeomlee** [comment]
저는 React.memo 사용시 eslint error가 없는데
어떤건지 잘 모르겠습니다

**Comment by jsc7727** [comment]
- (https://github.com/yannickcr/eslint-plugin-react/issues/2133)
eslint가 작동 안 하는 걸까요? 
이유를 모르겠네요.
일단은 이슈 닫겠습니다.
